name: desktop_gui
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  async: ^2.11.0
  basics: ^0.10.0
  built_collection: ^5.1.1
  collection: ^1.17.1
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  grpc: ^3.1.0
  path_provider: ^2.1.0
  flutter_svg: ^2.0.7
  tray_menu:
    git: https://github.com/andrei-toterman/tray_menu.git
  window_manager: ^0.3.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu-R.ttf
        - asset: assets/Ubuntu-B.ttf
          weight: 700
        - asset: assets/Ubuntu-L.ttf
          weight: 300
